#include "data.h"

Data::Data()
{
    capitals =
    {
        {"abu dabi", "obedineni arabski emirstva"},
        {"abuja", "nigeriq"},
        {"adis abeba", "etiopiq"},
        {"akra", "gana"},
        {"aljir", "aljir"},
        {"alofi", "niue"},
        {"aman", "yordaniq"},
        {"amsterdam", "holandiq"},
        {"amsterdam ", "niderlandiq"},
        {"andora la vela", "andora"},
        {"ankara", "turciq"},
        {"antananarivo", "madagaskar"},
        {"asmara", "eritreq"},
        {"astana", "kazahstan"},
        {"asunsion", "paragvai"},
        {"atina", "gurciq"},
        {"ashhabad", "turkmenistan"},
        {"bagdad", "irak"},
        {"baku", "azerbaijan"},
        {"bamako", "mali"},
        {"bandar seri begavan", "brunei"},
        {"bangi", "centralnoafrikanskata republika"},
        {"banjul", "gambiq"},
        {"bankok", "tailand"},
        {"baster", "seint kic i nevis"},
        {"beirut", "livan"},
        {"belgrad", "sarbiq"},
        {"belmopan", "beliz"},
        {"berlin", "germaniq"},
        {"bern", "shveicariq"},
        {"bishkek", "kirgizstan"},
        {"bisau", "gvineq-bisau"},
        {"blumfontein", "republika iujna afrika"},
        {"bogota", "kolumbiq"},
        {"brazavil", "kongo"},
        {"bratislava", "slovakiq"},
        {"brijtaun", "barbados"},
        {"briuksel", "belgiq"},
        {"budapeshta", "ungariq"},
        {"buenos aires", "arjentina"},
        {"bujumbura", "burundi"},
        {"bukuresht", "rumaniq"},
        {"vaduc", "lihtenshtain"},
        {"valeta", "malta"},
        {"varshava", "polsha"},
        {"vatikana", "vatikana"},
        {"vashington", "sasht"},
        {"viena", "avstriq"},
        {"vientqn", "laos"},
        {"vilnius", "litva"},
        {"vindhuk", "namibiq"},
        {"gaborone", "bocvana"},
        {"gvatemala", "gvatemala"},
        {"daka", "bangladesh"},
        {"dakar", "senegal"},
        {"damask", "siriq"},
        {"dar es salaam", "tanzaniq"},
        {"jakarta", "indoneziq"},
        {"jibuti", "jibuti"},
        {"jorjtaun", "gviana"},
        {"dili", "iztochen timor"},
        {"dodoma", "tanzaniq"},
        {"doha", "katar"},
        {"dushanbe", "tajikistan"},
        {"dablin", "irlandiq"},
        {"el aiun", "zapadna sahara"},
        {"erevan", "armeniq"},
        {"zagreb", "harvatiq"},
        {"islamabad", "pakistan"},
        {"kabul", "afganistan"},
        {"kairo", "egipet"},
        {"kampala", "uganda"},
        {"kanbera", "avstraliq"},
        {"karakas", "venecuela"},
        {"kastriis", "seint lusiq"},
        {"katmandu", "nepal"},
        {"keiptaun", "republika iujna afrika"},
        {"kigali", "ruanda"},
        {"kiev", "ukraina"},
        {"kingstaun", "seint vinsent i grenadini"},
        {"kingstan", "qmaika"},
        {"kinshasa", "demokratichna republika kongo"},
        {"kito", "ekvador"},
        {"kishinev", "moldova"},
        {"konakri", "gvineq"},
        {"kopenhagen", "daniq"},
        {"kuala lumpur", "malaiziq"},
        {"kuveit", "kuveit"},
        {"la pas", "boliviq"},
        {"libarvil", "gabon"},
        {"lilongve", "malavi"},
        {"lima", "peru"},
        {"lisabon", "portugaliq"},
        {"lobamba", "esvatini"},
        {"lome", "togo"},
        {"london", "velikobritaniq"},
        {"london ", "angliq"},
        {"luanda", "angola"},
        {"lusaka", "zambiq"},
        {"liublqna", "sloveniq"},
        {"liuksemburg", "liuksemburg"},
        {"majuro", "marshalovi ostrovi"},
        {"madrid", "ispaniq"},
        {"malabo", "ekvatorialna gvineq"},
        {"male", "maldivi"},
        {"managua", "nikaragua"},
        {"manama", "bahrein"},
        {"manila", "filipini"},
        {"maputo", "mozambik"},
        {"maseru", "lesoto"},
        {"maskat", "oman"},
        {"mbabane", "esvatini"},
        {"meksiko", "meksiko"},
        {"ngerulmud", "palau"},
        {"minsk", "belarus"},
        {"mogadishu", "somaliq"},
        {"monako", "monako"},
        {"monroviq", "liberiq"},
        {"montevideo", "urugvai"},
        {"moroni", "komorski ostrovi"},
        {"moskva", "rusiq"},
        {"naipidal", "mianmar"},
        {"nairobi", "keniq"},
        {"nasau", "bahamski ostrovi"},
        {"njamena", "chad"},
        {"niamei", "niger"},
        {"nikoziq", "kipar"},
        {"nuakshot", "mavritaniq"},
        {"nuku'alofa", "tonga"},
        {"nuuk", "grenlandiq"},
        {"niu delhi", "indiq"},
        {"oslo", "norvegiq"},
        {"otava", "kanada"},
        {"palikir", "mikroneziq"},
        {"panama", "panama"},
        {"paramaribo", "surinam"},
        {"parij", "franciq"},
        {"pekin", "kitai"},
        {"pnom pen", "kamboja"},
        {"podgorica", "cherna gora"},
        {"port vila", "vanuatu"},
        {"port lui", "mavricii"},
        {"port morsbi", "papua nova gvineq"},
        {"port o prens", "haiti"},
        {"port af spein", "trinidad i tobago"},
        {"porto novo", "benin"},
        {"praga", "chehiq"},
        {"praq", "kabo verde"},
        {"pretoriq", "republika iujna afrika"},
        {"phenqn", "severna koreq"},
        {"rabat", "maroko"},
        {"reikqvik", "islandiq"},
        {"riga", "latviq"},
        {"rim", "italiq"},
        {"riqd", "saudicka arabiq"},
        {"rozo", "dominika"},
        {"san marino", "san marino"},
        {"san salvador", "salvador"},
        {"san hose", "kosta rika"},
        {"san huan", "puerto riko"},
        {"sana", "yemen"},
        {"edinburg", "shotlandiq"},
        {"santo domingo", "dominikanska republika"},
        {"santqgo de chile", "chili"},
        {"sao tome", "sao tome i prinsipi"},
        {"saraevo", "bosna i hercegovina"},
        {"seint jorjes", "grenada"},
        {"seint jons", "antigua i barbuda"},
        {"seul", "iujna koreq"},
        {"singapur", "singapur"},
        {"skopie", "severna makedoniq"},
        {"sofia", "bulgaria"},
        {"sofiq", "bulgariq"},
        {"stokholm", "shveciq"},
        {"sukre", "boliviq"},
        {"suva", "fiji"},
        {"taipe", "taivan"},
        {"talin", "estoniq"},
        {"tashkent", "uzbekistan"},
        {"tbilisi", "gruziq"},
        {"tegusigalpa", "honduras"},
        {"teheran", "iran"},
        {"tirana", "albaniq"},
        {"tokio", "qponiq"},
        {"tripoli", "libiq"},
        {"tunis", "tunis"},
        {"thimphu", "butan"},
        {"uagadugu", "burkina faso"},
        {"wellington", "nova zelandiq"},
        {"ulan bator", "mongoliq"},
        {"friitaun", "siera leone"},
        {"funafuti", "tuvalu"},
        {"havana", "kuba"},
        {"hanoi", "vietnam"},
        {"harare", "zimbabve"},
        {"hartum", "sudan"},
        {"helzinki", "finlandiq"},
        {"honiara", "solomonovi ostrovi"},
        {"shri jaqvardanapura kote", "shri lanka"},
        {"iujna tarava", "kiribati"},
        {"qmusukro", "kot d'ivoar"},
        {"qren", "nauru"},
        {"qunde", "kamerun"},
    };

    codes =
    {
        {"af", "Afrikaans"},
        {"sq", "Albanian"},
        {"am", "Amharic"},
        {"ar", "Arabic"},
        {"hy", "Armenian"},
        {"az", "Azerbaijani"},
        {"eu", "Basque"},
        {"be", "Belarusian"},
        {"bn", "Bengali"},
        {"bs", "Bosnian"},
        {"bg", "Bulgarian"},
        {"ca", "Catalan"},
        {"ceb", "Cebuano"},
        {"ny", "Chichewa"},
        {"zh", "Chinese"},
        {"co", "Corsican"},
        {"hr", "Croatian"},
        {"cs", "Czech"},
        {"da", "Danish"},
        {"nl", "Dutch"},
        {"en", "English"},
        {"eo", "Esperanto"},
        {"et", "Estonian"},
        {"tl", "Filipino"},
        {"fi", "Finnish"},
        {"fr", "French"},
        {"fy", "Frisian"},
        {"gl", "Galician"},
        {"ka", "Georgian"},
        {"de", "German"},
        {"el", "Greek"},
        {"gu", "Gujarati"},
        {"ht", "Hausa"},
        {"haw", "Hawaiian"},
        {"iw", "Hebrew"},
        {"hi", "Hindi"},
        {"hmn", "Hmong"},
        {"hu", "Hungarian"},
        {"is", "Icelandic"},
        {"ig", "Igbo"},
        {"id", "Indonesian"},
        {"ga", "Irish"},
        {"it", "Italian"},
        {"ja", "Japanese"},
        {"jw", "Javanese"},
        {"kn", "Kannada"},
        {"kk", "Kazakh"},
        {"km", "Khmer"},
        {"rw", "Kinyarwanda"},
        {"ko", "Korean"},
        {"ku", "Kyrgyz"},
        {"lo", "Lao"},
        {"la", "Latin"},
        {"lv", "Latvian"},
        {"lt", "Lithuanian"},
        {"lb", "Luxembourgish"},
        {"mk", "Macedonian"},
        {"mg", "Malagasy"},
        {"ms", "Malay"},
        {"ml", "Malayalam"},
        {"mt", "Maltese"},
        {"mi", "Maori"},
        {"mr", "Marathi"},
        {"mn", "Mongolian"},
        {"my", "Nepali"},
        {"no", "Norwegian"},
        {"or", "Pashto"},
        {"fa", "Persian"},
        {"pl", "Polish"},
        {"pt", "Portuguese"},
        {"pa", "Punjabi"},
        {"ro", "Romanian"},
        {"ru", "Russian"},
        {"sm", "Samoan"},
        {"gd", "Serbian"},
        {"st", "Sesotho"},
        {"sn", "Shona"},
        {"sd", "Sindhi"},
        {"si", "Sinhala"},
        {"sk", "Slovak"},
        {"sl", "Slovenian"},
        {"so", "Somali"},
        {"es", "Spanish"},
        {"su", "Sundanese"},
        {"sw", "Swahili"},
        {"sv", "Swedish"},
        {"tg", "Tajik"},
        {"ta", "Tamil"},
        {"tt", "Tatar"},
        {"te", "Telugu"},
        {"th", "Thai"},
        {"tr", "Turkish"},
        {"tk", "Turkmen"},
        {"uk", "Ukrainian"},
        {"ur", "Urdu"},
        {"ug", "Uyghur"},
        {"uz", "Uzbek"},
        {"vi", "Vietnamese"},
        {"cy", "Welsh"},
        {"xh", "Xhosa"},
        {"yi", "Yiddish"},
        {"yo", "Yoruba"},
        {"zu", "Zulu"}
    };

    codesCount = codes.count();

    for (auto it = capitals.constKeyValueBegin();
         it != capitals.constKeyValueEnd();
         it++)
    {
        countries.insert(it->second, it->first);
    }
}
